Issue #BIB-239: Logger service to send message to backend logs
bibboxen/bibbox pull request #5
Opened 2017-03-10 13:54 UTC by cableman

2017-03-10 14:10 UTC, tuj requested changes

2017-03-10 14:10 UTC, tuj commented on public/js/services/loggerService.js
> + * @TODO: If in debug mode also log to console.
Yeah... also what I thought was missing

2017-03-10 14:10 UTC, tuj commented on public/js/services/userService.js
> +    proxyService.emit('logger.frontend', 'TEST TEST');
Remove :)

2017-03-10 14:29 UTC, cableman commented on public/js/services/loggerService.js
> + * @TODO: If in debug mode also log to console.
Yes, just not sure if we have a debug mode in the front-end?

2017-03-10 14:30 UTC, cableman commented on public/js/services/userService.js
> +    proxyService.emit('logger.frontend', 'TEST TEST');
done

2017-03-13 09:27 UTC, cableman commented on public/js/services/loggerService.js
> + * @TODO: If in debug mode also log to console.
Done

2017-03-13 09:35 UTC, tuj approved these changes

2017-03-13 09:38 UTC, merged